# Generated by Django 5.0.1 on 2024-01-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0003_alter_idea_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="작성일"),
        ),
        migrations.AlterField(
            model_name="idea",
            name="tool",
            field=models.CharField(choices=[], max_length=24, verbose_name="예상 개발툴"),
        ),
        migrations.AlterField(
            model_name="idea",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
    ]
