# Generated by Django 5.0.1 on 2024-01-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0004_alter_idea_created_date_alter_idea_tool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="created_date",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, verbose_name="작성일"
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="tool",
            field=models.CharField(
                choices=[
                    ("Django", "Django"),
                    ("Django", "Django"),
                    ("React", "React"),
                ],
                max_length=24,
                verbose_name="예상 개발툴",
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="updated_date",
            field=models.DateTimeField(
                auto_created=True, auto_now=True, verbose_name="수정일"
            ),
        ),
    ]
