# Generated by Django 5.0.1 on 2024-01-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0005_alter_idea_created_date_alter_idea_tool_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="star",
            field=models.BooleanField(default=False),
        ),
    ]
