# Generated by Django 5.0.1 on 2024-01-21 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
        ("posts", "0004_remove_post_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.post",
            ),
        ),
    ]
