# Generated by Django 5.0.1 on 2024-01-21 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_comment_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="post",
        ),
    ]
