# Generated by Django 5.0.1 on 2024-01-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
        ("posts", "0002_alter_post_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="comments.comment",
            ),
        ),
    ]
